macos: Fix compile on aarch64
rust-windowing/winit pull request #1752
Opened 2020-11-02 20:31 UTC by scoopr

Fixes compilation when targeting aarch64, where `objc` crate has slightly different encoding for `BOOL` type.

2020-11-02 20:34 UTC, kchibisov requested changes
You should add a CHANGELOG entry for that, other than that it should be fine as long as tests are passing.

2020-11-02 20:58 UTC, scoopr commented
Changelog updated, tests passed.

2020-11-02 21:05 UTC, chrisduerr approved these changes

2020-11-02 21:06 UTC, merged

2020-12-17 01:36 UTC, jrmuizel commented
Is it possible for us to backport this to 0.19 branch?

2020-12-17 01:41 UTC, kchibisov commented
The 0.19 is dead and there's no intent to support it upstream, since some backends won't start on it anymore. If you want 0.19 version, you're free to maintain it yourself.

2021-03-03 09:20 UTC, philip-lamb commented
> The 0.19 is dead and there's no intent to support it upstream, since some backends won't start on it anymore. If you want 0.19 version, you're free to maintain it yourself.

@kchibisov Do you mean that if I make a pull request against 0.19.x to apply this patch, it will be rejected? Since Servo is currently stuck on 0.19.x, we will have to fork this repo if we can't get this patch landed here on the 0.19.x branch.

2021-03-03 15:55 UTC, maroider commented
> Servo is currently stuck on 0.19.x

While this is true, there is some progress happening in [this PR](https://github.com/servo/servo/pull/28236#issue-583853665).