Added focus_window to Window
rust-windowing/winit pull request #1767
Opened 2020-11-16 10:32 UTC by maxded

Fixes #1750

`Window::focus_window` brings the window to the front and sets input focus to that window. As described in the documentation, this method steals focus from other applications and should be used with care. Even though this method can cause quite a disruptive user experience I do believe winit should provide the option to users of this crate as valid use cases exist.

Decided to call it `focus_window` but the name could be changed for more clarity. Some APIs, like `set_minimized`, have a boolean parameter for toggling the, in this case, "minimized" state. For `focus_window` I decided not to do that as "unfocusing" is quite strange, like, where does the focus go? Also deliberately made the choice to "ignore" `focus_window` on minimized and not visible windows for improved user experience.

Don't have a Linux X11 machine at my disposal so the implementation might/is probably incorrect.

- [ ] Tested on all platforms changed
Tested on Windows and macOS.
- [ ] `cargo fmt` has been run on this branch
- [ ] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior

2020-11-16 10:43 UTC, chrisduerr commented
> Even though this method can cause quite a disruptive user experience I do believe winit should provide the option to users of this crate as valid use cases exist.

You're saying this, but you're not providing any of those valid usecases. I'd be curious what those would be, especially since this isn't even possible on all platforms.

Generally I think it's pretty useless for winit to be the arbiter of what is morally right or wrong, but winit should definitely be the place to decide if something has a valid usecase, or if it is just a useless API that will lock people into a design that will cause failure when trying to make it work for other platforms.

So I personally think this should be very carefully questioned before being added. Only because it's easy to add, doesn't mean it's a good idea.

2020-11-16 10:45 UTC, chrisduerr requested changes

2020-11-16 10:45 UTC, chrisduerr commented on src/platform_impl/linux/x11/window.rs
> +    }
This code is dead? If the goal was to call this with the `focus_window_inner` call, I don't see why it wouldn't just be inlined?

2020-11-16 11:15 UTC, maxded commented
One use case would be opening links to your application. For example, Discord provides links users can click on to join a Discord server. The user expects, when clicking the link, to be brought to that server by opening/bringing Discord to the front and show the newly joined server. In these use cases, the user knows that it will be redirected to the application and focus stealing is ok. 

Instead of focusing the window when clicking a link, Discord could have gone the `request_user_attention` route but that just introduces another step the user has to take, which they, in most cases, don't want. (The link has clear intention).

> So I personally think this should be very carefully questioned before being added. Only because it's easy to add, doesn't mean it's a good idea.

Agreed! Part of the reasoning behind this PR is to spark discussion :)

2020-11-16 11:20 UTC, chrisduerr commented
> One use case would be opening links to your application. For example, Discord provides links users can click on to join a Discord server. The user expects, when clicking the link, to be brought to that server by opening/bringing Discord to the front and show the newly joined server. In these use cases, the user knows that it will be redirected to the application and focus stealing is ok.

Shouldn't that be handled by whatever mechanism decides which application to open a link with? I suppose that's kinda fair if an application is just re-executed or receives some event without getting focus assigned.

2020-11-16 11:31 UTC, kchibisov commented
I'm actually not sure how it should be done on X11 for raising window there's a https://specifications.freedesktop.org/startup-notification-spec/startup-notification-latest.txt , and for Wayland there will be similar protocol (it's under development now https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/50).

2021-01-31 16:30 UTC, artursapek commented
This would be useful for applications that can handle custom URL schemes - an already-running application that handles a link click from a web browser could bring itself to the foreground to indicate to the user that that is where the link click was handled.

2021-05-08 11:17 UTC, repi commented
Since we (Embark) created this PR we've been using it in production now for 6 months on Windows, Linux, Mac x86 and Mac aarch64 without any problems, specifically use it as one of our apps handles URLs and needs to bring the app window into focus when clicking a link. And has been working fine and reliable.

What would be needed to make some progress on this and get it in? Would be nice to get off our fork of winit

2021-05-08 13:55 UTC, ArturKovacs commented
I tried this on macOS with the following code. I run it with `cargo run`, quickly click on another window after the winit window shows up, but after "Focusing" gets printed, nothing seems to change, the winit window remains in the background.

```rust
use winit::{
    dpi::LogicalSize,
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};
fn main() {
    let event_loop = EventLoop::new();
    // event_loop.set_activation_policy(ActivationPolicy::Accessory);
    let window = WindowBuilder::new()
        .with_title("my fantastic window ")
        .with_inner_size(LogicalSize::new(200, 50))
        .build(&event_loop)
        .unwrap();
    let start = std::time::Instant::now();
    let mut focused = false;
    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Poll;
        if start.elapsed().as_secs_f32() > 4.0 && !focused {
            println!("Focusing");
            window.focus_window();
            focused = true;
        }
        match event {
            Event::WindowEvent { event, .. } => match event {
                WindowEvent::CloseRequested => *control_flow = ControlFlow::Exit,
                _ => (),
            },
            _ => (),
        }
    });
}

```

I tried merging master into this, and also tried calling `activateIgnoringOtherApps_` right after `makeKeyAndOrderFront_`, with no success.

Note that there's another PR, #1868 that implements this in a slightly different way. I could not get that to work either, so it's probably just my system. With that, the code seems fine so I'm willing to approve this for macOS. @msiglreith at this point I'm willing to approve both of these PRs, although I would request a change for the other PR. I could also test this for X11, and I think @maroider can test for X11 as well. So if you don't mind I'd like to ask you to decide which one we should go with.

2021-05-15 12:21 UTC, msiglreith commented
@ArturKovacs Ah sorry, I missed your question at the end somehow. For the Windows impl I'm slightly favoring this one, but the other one is fine as well. If someone is willing to approve the x11 parts we can go with this one as it's more complete/cross-platform.

2021-05-16 20:35 UTC, ArturKovacs commented
Yeah, I'll take responsibility for reviewing the X11 implementation for this. I fixed the compiler errors and then tested on X11. It works as expected. @maxded do you mind if I push my fixes along with some minor changes in X11 to this branch?

2021-05-17 07:07 UTC, maxded commented
@ArturKovacs go ahead!

2021-05-17 16:44 UTC, ArturKovacs commented
I can't push here, the branch name is not a link so I don't know what's the remote for it. (I pushed into a new `window_focus` branch in this repo, but that's not very helpful) Please help :D

![Screenshot from 2021-05-17 18-39-22](https://user-images.githubusercontent.com/8320264/118525750-d4721100-b73f-11eb-9627-7866a28dd51e.png)

2021-05-17 17:01 UTC, maxded commented
@ArturKovacs that is my bad, I think I've accidentally removed the branch some time ago. Should we continue this feature/PR from your new branch or should I revive mine and go from there?

2021-05-17 17:15 UTC, ArturKovacs commented
I'd just like to continue under this PR if that's possible, but otherwise it really doesn't make a difference I think.

2021-05-18 14:44 UTC, closed without merging