WIPadd is_maximized for x11
rust-windowing/winit pull request #1848
Opened 2021-02-02 01:52 UTC by garasubo

- [ ] Tested on all platforms changed
- [ ] Compilation warnings were addressed
- [ ] `cargo fmt` has been run on this branch
- [ ] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2021-02-12 04:29 UTC, garasubo commented
Could anyone review this PR?

2021-02-20 05:40 UTC, garasubo commented
@murarth Could you review this PR?

2021-06-09 22:14 UTC, kchibisov requested changes
This looks fine(I can add Wayland impl later), however, could you add a changelog entry for that, thx.

2021-06-09 23:30 UTC, kchibisov commented
I've taken the liberty to rebase your PR and also added a Wayland implementation to it, should be good to go once CI pass.

2021-06-10 07:43 UTC, merged

2021-06-11 05:59 UTC, garasubo commented
@kchibisov Thanks for adding Wayland implementation!