Mac: Redraw immediately to prevent shaking on window resize
rust-windowing/winit pull request #1901
Opened 2021-04-04 17:23 UTC by xiaopengli89

Fixes #1837, gfx-rs/wgpu-rs#536, rust-windowing/glutin#1340, servo/webrender#1640

2021-04-04 19:25 UTC, ArturKovacs commented
At a first glance this seems to be related to or a duplicate of #1812, but I'm going to give a proper review later.

2021-04-05 11:32 UTC, ArturKovacs commented
I was wrong, this addresses different problem than #1812.

2021-04-05 11:37 UTC, ArturKovacs requested changes
This looks perfect, but please add an entry to the `CHANGELOG.md` file, something like:
```
- On macOS, emit `RedrawRequested` events while the window is being resized.
```

2021-04-06 03:50 UTC, xiaopengli89 commented
Alright, and thanks for your review.

2021-04-06 04:59 UTC, maroider commented on CHANGELOG.md
> +- On macOS, emit `RedrawRequested` events while the window is being resized.
```suggestion
- On macOS, emit `RedrawRequested` events immediately while the window is being resized.
```
Based on the PR title, linked issues, and the tiny amount of code I've seen in the macOS backend, this seems like it describes the changes better.

2021-04-06 07:22 UTC, merged