Windows: Increase wait timer resolution
rust-windowing/winit pull request #2007
Opened 2021-08-22 11:20 UTC by msiglreith

Addresses #2005 

Temporarily increase the timer resolution for the wait operation. By default it's around 16ms which is too long for most realtime applications and leads to unpredictable results. A future enhancement in this direction could be allow the user to control it. Possible use case would be UI application with some animations running with minimal energy impact.

Reported by https://twitter.com/olson_dan/status/1428840173354160128?s=20
With the given change for the wgpu `water` example the framerate is much closer to the target of 16.6ms on my system.

Before
```
Avg frame time 28.707153ms
Avg frame time 28.356724ms
Avg frame time 28.303003ms
Avg frame time 28.835732ms
Avg frame time 29.122643ms
Avg frame time 27.729534ms
```

After
```
Avg frame time 16.845396ms
Avg frame time 16.859407ms
Avg frame time 16.840519ms
Avg frame time 16.862593ms
Avg frame time 16.856462ms
Avg frame time 16.870092ms
Avg frame time 16.868887ms
```

- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [ ] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2021-08-23 12:47 UTC, filnet commented on src/platform_impl/windows/event_loop.rs
> +        mmsystem::TIMECAPS,
i suggest using mssystem not mmsystem::TIMECAPS.
seems to be the approach used here.

2021-08-23 12:51 UTC, filnet commented on src/platform_impl/windows/event_loop.rs
> +        timeapi::timeGetDevCaps(&mut tc as *mut _, mem::size_of::<TIMECAPS>() as _);
check and handle errors ?
if the call errors out, then wPeriodMin could be undefined.

2021-11-02 18:22 UTC, maroider requested changes
I did a once-over and marked everything that looked to be resolved as "resolved".
I only have a couple of nitpicks.

2021-11-02 18:22 UTC, maroider commented on src/platform_impl/windows/event_loop.rs
> +                    // `WaitUntil`, so we request the Windows' scheduler to use a higher accuracy if possible.
```suggestion
                    // `WaitUntil`, so we request the Windows scheduler to use a higher accuracy if possible.
```
nit: This sentence feels weird. Removing the apostrophe makes it feel less so.

2021-11-02 18:22 UTC, maroider commented on CHANGELOG.md
> +
Idk why, but there's an extra newline here.

2021-11-02 20:09 UTC, msiglreith commented
Thanks for reviewing again, addressed the remaining parts

2021-11-02 20:29 UTC, maroider approved these changes

2021-11-02 20:51 UTC, merged