Add touchpad magnify support for macOS
rust-windowing/winit pull request #2157
Opened 2022-01-20 18:19 UTC by jsatka

Add touchpad two-finger pinch gesture support for macOS.

Adds new event `WindowEvent::TouchpadMagnify`, where positive delta values indicate magnification (zooming in) and
negative delta values indicate shrinking (zooming out).

Checklist
- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2022-01-20 21:26 UTC, jsatka commented
Fixed formatting

2022-01-23 13:09 UTC, madsmtm reviewed
Haven't looked much at the implementation, but really I'm not sure I can justify this feature belonging to `winit`? Is it possible to support these gestures on other platforms?

2022-01-23 14:53 UTC, jsatka commented
> Is it possible to support these gestures on other platforms?

Judging by documentations it should:
- Wayland supports both: [libinput > Gestures](https://wayland.freedesktop.org/libinput/doc/latest/gestures.html)
- Windows supports magnify only: [Touch gestures for Windows](https://support.microsoft.com/en-us/windows/touch-gestures-for-windows-a9d28305-4818-a5df-4e2b-e5590f850741)

2022-01-23 15:12 UTC, jsatka commented on src/platform_impl/macos/view.rs
> +            NSEventPhase::NSEventPhaseEnded => TouchPhase::Ended,
It does make sense adding `NSEventPhaseCancelled => TouchPhase::Cancelled,` mapping indeed. Will include it.

In the context of these gestures the `NSEventPhaseMayBegin` would mean that user has placed two fingers on trackpad, which could be a beginning for multiple types of two-finger gestures. `NSEventPhaseBegan` will always be reported once AppKit detects beginning of specific type of gesture.

2022-01-24 09:22 UTC, dhardy commented
> I'm not sure I can justify this feature belonging to winit?

It sounds like integration with regular desktop input facilities to me, given that the desktop platform is responsible for reporting gestures (not raw touchpad input), so I'd say yes, this belongs in Winit.

Would it make more sense to report `WindowEvent::Gesture(device_id, phase, Gesture::Magnify)` etc, given the possibility of adding `Swipe` and `Hold` in the future?

2022-01-24 14:34 UTC, jsatka commented
> Would it make more sense to report `WindowEvent::Gesture(device_id, phase, Gesture::Magnify)` etc, given the possibility of adding `Swipe` and `Hold` in the future?

Gesture types may have different requirements for reporting the delta, such as swipe gesture having either a direction as additional parameter, or delta as x and y components. But workarounds do exist; swipes could be split into vertical and horizontal swipe types and while hold gesture doesn't technically have a delta it could just be reported always as zero.

I think it is mainly a matter of opinion, which way of reporting is better. Personally I'd prefer a flat structure, so that as an application developer I can add handling for a single type of gesture without additional layers of match arms. But that's just my two cents.

2022-08-10 16:48 UTC, madsmtm requested changes
Fair, I've changed my mind, I agree that we should have this in `winit`, at least for the time being.

I think there is merit in exploring an API for "zoom" and "rotate" in general (e.g. not something specific to touchpads), but not something I want to block this PR further on, that can always be added later.

I don't have permissions to touch your branch, so would you mind merging the latest `master` and fixing the conflicts?

2022-08-10 16:48 UTC, madsmtm commented on examples/touchpad_gestures.rs
> +                        println!("Rotated right {}", delta);
Nit:

```suggestion
                        println!("Rotated counterclockwise {}", delta);
                    } else {
                        println!("Rotated clockwise {}", delta);
```

2022-08-10 16:48 UTC, madsmtm commented on src/event.rs
> +    /// At the moment, only supported on macOS.
Nit: Use the usual `## Platform-specific` header

2022-08-10 16:48 UTC, madsmtm commented on src/event.rs
> +    /// negative delta values indicate rotation to right (clockwise).
Nit: "counterclockwise" and "clockwise" are the correct and precise terms for this, just always use those.

2022-08-10 17:00 UTC, madsmtm commented on src/platform_impl/macos/view.rs
> +            NSEventPhase::NSEventPhaseEnded => TouchPhase::Ended,
I was going to argue that I'd want the behaviours here to be similar to when scrolling, but it seems like `NSEventPhaseMayBegin` is never actually used in `magnifyWithEvent:` and `rotateWithEvent:`, so yeah, probably fine as it is

2022-08-16 13:30 UTC, jsatka commented
Latest `master` is now merged with all checks fixed.

2022-08-16 13:45 UTC, madsmtm reviewed
Thanks! Just a few more fixes if you wouldn't mind?

2022-08-16 13:45 UTC, madsmtm commented on src/event.rs
> +    /// At the moment, only supported on macOS.
Nit: Use `## Platform-specific` section

2022-08-16 13:45 UTC, madsmtm commented on src/platform_impl/macos/view.rs
> +    trace!("Triggered `rotateWithEvent`");
Nit: Use `trace_scope!` macro (and remove `trace` at the end of this function)

2022-08-16 13:45 UTC, madsmtm commented on src/platform_impl/macos/view.rs
> +    trace!("Triggered `magnifyWithEvent`");
Nit: Use `trace_scope!` macro (and remove `trace` at the end of this function)

2022-08-16 15:19 UTC, madsmtm approved these changes

2022-08-16 15:20 UTC, merged

2022-08-16 15:20 UTC, madsmtm commented
No worries!

2022-12-20 21:51 UTC, emilk commented
I'm eagerly awaiting this to be published in the next winit release!