Make winit focus take activity into account on Windows
rust-windowing/winit pull request #2159
Opened 2022-01-22 14:48 UTC by swooster

Fix for issue #2102

`winit`'s notion of "focus" is very simple; you're either focused or not.
However, Windows has both notions of focused window and active window
and paying attention only to `WM_SETFOCUS`/`WM_KILLFOCUS` can cause a window
to believe the user is interacting with it when they're not. (this
manifests when a user switches to another application between when a
`winit` application starts and it creates its first window)

2022-01-22 14:49 UTC, swooster commented
Pinging @maroider

2022-07-06 13:24 UTC, maroider reviewed
This all seems quite sensible. I'd just like to test this and have the conflicts resolved, and then approve it.

> The code looks good to me, but I am not a winit reviewer.

I appreciate that you took the time to look at it either way :)

2022-07-06 17:46 UTC, swooster commented
Ok, I've pushed a new version that shouldn't have any conflicts. I wasn't really happy with how it now compares a `wparam` to 1 instead of the win32 API's `TRUE`, but I had trouble finding a proper `TRUE` constant in `windows-sys`.

2022-07-07 08:43 UTC, maroider requested changes

2022-07-07 09:01 UTC, maroider commented
Alright. I've reproduced the original issue, and this PR looks like it works as advertised.

2022-07-07 12:16 UTC, swooster commented on src/platform_impl/windows/event_loop.rs
> +            let is_active = wparam == 1; // TODO: figure out windows_sys equivalent of TRUE?
Feel free to remove that... I guess I had left it both as a reminder to myself and to sorta say "this `1` is supposed to be a win32 API `TRUE` constant". Hmm... think I should just create a const named `TRUE` somewhere?

2022-07-08 19:08 UTC, swooster commented
(applied suggested fix, realized I forgot to update the changelog, and rebased)

2022-07-15 00:25 UTC, maroider commented on CHANGELOG.md
> +- Fix focus events being sent to inactive windows on Windows.
```suggestion
- On Windows, fix focus events being sent to inactive windows.
```

2022-07-15 01:18 UTC, maroider approved these changes

2022-07-15 08:27 UTC, msiglreith approved these changes

2022-07-15 08:27 UTC, merged