On Windows, fix left mouse button release event not being sent on drag finish
rust-windowing/winit pull request #2200
Opened 2022-02-19 17:55 UTC by feelingnothing

After tricking windows into thinking we are pressing on `HTCAPTION`, we would not get `WM_NCLBUTTONUP`, thus creating unexpected behavior in `winit` dependent projects (https://github.com/emilk/egui/issues/1245#issue-1134534176)
Some debugging after it appears that `wine` have different logic that `winapi` (for context see [this](https://matrix.to/#/!DGpLzJTRzBDTwZiogk:matrix.org/$8hlJG0C6Eiorsj0suXpUr5IOXx0if1nhIfPRHoMwZI8?via=matrix.org&via=libera.chat))

With event tracing we can see that the most suitable event triggered on every drag is `WM_EXITSIZEMOVE`([docs](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-exitsizemove)):
![image](https://user-images.githubusercontent.com/47575622/154812898-9f1b1b3b-ef6c-4e59-bdca-f2579e43a4fb.png)

- Fixes: https://github.com/rust-windowing/winit/issues/2192

2022-03-28 22:32 UTC, emilk commented
I'd be interested in seeing this merged! the `drag_window` feature is critical for users that want to draw their own window frame.

2022-03-31 20:32 UTC, msiglreith requested changes
Thanks, but this leads to undesired `Released` events if we are actually dragging inside the `HTCAPTION` area.
One idea could be to instead emit a message with `HTCLIENT` instead of `HTCAPTION` on `drag_window`, use it as indicator that it's a user generated event in the event loop, but forwarding `HTCAPTION` to `DefWindowProc` to internally let it do the dragging stuff for us..

2022-03-31 20:53 UTC, maroider commented
Can't we just set the flag inside [`Window::drag_window`](https://github.com/rust-windowing/winit/blob/2ae12fb0a0f5c81e5c1ab5c690bbe5a138368ca0/src/platform_impl/windows/window.rs#L339-L360). `Window` should have access to `WindowState`.

2022-04-02 16:31 UTC, feelingnothing commented
> Can't we just set the flag inside [`Window::drag_window`](https://github.com/rust-windowing/winit/blob/2ae12fb0a0f5c81e5c1ab5c690bbe5a138368ca0/src/platform_impl/windows/window.rs#L339-L360)? `Window` should have access to `WindowState`.
I mean there is no difference, anyways to have to check for `HTCAPTION` in `WM_NCLBUTTONDOWN`, either we do it in `drag_window` or in event handler doesn't matter. I like how it makes all dragging logic in dragging function, but check for `HTCAPTION` is dragging logic too.

2022-04-02 16:36 UTC, feelingnothing commented
> Thanks, but this leads to undesired `Released` events if we are actually dragging inside the `HTCAPTION` area. One idea could be to instead emit a message with `HTCLIENT` instead of `HTCAPTION` on `drag_window`, use it as indicator that it's a user generated event in the event loop, but forwarding `HTCAPTION` to `DefWindowProc` to internally let it do the dragging stuff for us..

I don't think there is a way to `Release` event to be emitted in unwanted situation, considering dragging flag in window state. With event logger from @maroider we can see that `WM_EXITSIZEMOVE` is the most suitable one. The windows api tells that this event is trigged in the end of every move or resize, considering the dragging flag I'm sure nothing out of ordinary would happend

2022-04-03 11:02 UTC, msiglreith commented
> Can't we just set the flag inside [Window::drag_window](https://github.com/rust-windowing/winit/blob/2ae12fb0a0f5c81e5c1ab5c690bbe5a138368ca0/src/platform_impl/windows/window.rs#L339-L360)? Window should have access to WindowState.

Right, I like this more under the light `drag_resize_window`. I guess we could even drop then the whole handling `NCLBUTTONDOWN` event.

> I don't think there is a way to Release event to be emitted in unwanted situation, considering dragging flag in window state.

Sorry if I wasn't clear on it. Normal dragging without `drag_window` using the native decorations from Windows will emit the same `HTCAPTION` message which we use for emulating. So in both cases the dragging flag will be set leading to the released event. In the case of native decorations this is not desired as we do not emit the corresponding Pressed event.

2022-04-03 23:39 UTC, maroider commented
> I guess we could even drop then the whole handling `NCLBUTTONDOWN` event.

We're handling that to fix an unrelated issue.

2022-11-22 19:33 UTC, closed without merging