Add methods to set ControlFlow
rust-windowing/winit pull request #2228
Opened 2022-03-27 09:25 UTC by swooster

Bare-bones `winit` applications must import many different types from `winit`... this PR reduces that by adding methods so `ControlFlow` can be updated without naming its type, hopefully resulting in minor simplifications to the examples.

- [ ] Tested on all platforms changed
 **(I've only tested on Windows, but I've run all examples)**
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented
 **(not applicable)**

2022-03-27 19:03 UTC, madsmtm commented
Huh, interesting idea! Not sure I'm really in favour, since it sort of hides the fact that you can query the current control flow.

If it's just the imports that bother you, we could consider making a prelude, though of course that has other disadvantages.

Regarding naming, maybe prefix the methods with `set_` or similar?

2022-03-27 20:14 UTC, maroider commented
I'm personally mostly OK with the proposed API, mostly because I find that method calls would be slightly more convenient to type out than `*control_flow = ControlFlow::Whatever`. The import isn't really that bothersome to me.

2022-03-28 15:48 UTC, swooster commented
I'm happy to prefix everything with `set_`. It now occurs to me that e.g. `control_flow.wait_until(instant);` could be mistaken for something that blocks immediately and `control_flow.set_wait_until(instant);` seems less likely to be misleading.

I'm _extremely_ wary of crate preludes after being subjected to wildcard-import-heavy code at my day job; I prefer to look for ways to avoid needing to do that.

Admittedly, importing `ControlFlow` isn't _that_ big a deal. It's just that after noticing this relatively simple tweak could shave off an import and eliminate redundant mentions of "control flow" from each control flow change, I figured it'd be worth suggesting via a PR.

2022-03-30 12:05 UTC, swooster commented
(ok, I've changed the names to prefix everything with `set_`)

2022-03-31 21:04 UTC, maroider approved these changes
LGTM

2022-04-03 10:47 UTC, swooster commented
(resolved conflicts)

2022-04-09 17:40 UTC, kchibisov requested changes

2022-04-09 17:40 UTC, kchibisov commented on CHANGELOG.md
> +- Added `ControlFlow::set_poll`, `ControlFlow::set_wait`, `ControlFlow::set_wait_until`, `ControlFlow::set_exit_with_code`, and `ControlFlow::set_exit` methods so typical apps can avoid importing `Co
I don't like how long this is, could be shorter, like
```suggestion
- Added helper methods on `ControlFlow` to set its value.
```

2022-04-09 18:06 UTC, kchibisov approved these changes

2022-04-09 18:12 UTC, swooster commented
(rebased and incorporated changelog suggestion)

2022-04-10 01:32 UTC, merged