macOS Add background color for Window
rust-windowing/winit pull request #2314
Opened 2022-06-05 13:16 UTC by rappet

Changing the background color on macOS is most useful for
changing the title bar color, as the content of the window will most likely be overwritten by the user.

- Add `WindowExtMacOS::set_background_color`
- Add `WindowBuilderExtMacOS::with_background_color`

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

Only changing the background color using new functionality (the title bar is also affected by this a bit):

<img width="368" alt="grafik" src="https://user-images.githubusercontent.com/5594651/172052069-4a89cac2-4d44-417a-ad12-cfeb4d1b37da.png">

Changing the background color and making the title bar transparent:

<img width="368" alt="grafik" src="https://user-images.githubusercontent.com/5594651/172052059-2979189d-d946-46b4-8ecb-2bfaf48bd299.png">

2022-06-05 13:19 UTC, rappet commented
One question that is open on my side is, if and how winit should handle colorspaces in the future,
as I did only implement bindings for sRGB in this case and macOS can support other color spaces for this (sRGB, P3, ...).

2022-06-06 23:49 UTC, madsmtm requested changes
Thanks, this probably makes sense to have.

sRGB is probably fine for now, that's also what our icons are using.

2022-06-06 23:49 UTC, madsmtm commented on src/platform_impl/macos/window.rs
> +                ns_window.setBackgroundColor_(color);
This is going to be overridden by a `setBackgroundColor_` call in `UnownedWindow::new` further down in this file, when `window.with_transparent(true)` has been called.

2022-06-06 23:49 UTC, madsmtm commented on src/platform_impl/macos/window.rs
> +            self.ns_window.setBackgroundColor_(ns_background);
This is very likely not thread safe, and should always be done on the main thread. As an example, try search for `set_title_async` to see how we do that.

2022-06-08 06:30 UTC, madsmtm commented
This can certainly be done by an external crate, just like `set_has_shadow`, `with_title_hidden`, and a lot of the other extra functionality we expose can.

But idk if it makes sense to have in our scope or not, my initial reaction was "yeah sure" because it's quite a small feature.

2022-08-05 13:03 UTC, Matts966 commented
As a [neovide](https://github.com/neovide/neovide) user, this is one of the most desireble features...

2022-08-05 13:49 UTC, Matts966 commented
`NSWindow` is greatly abstracted by `winit` and it seems difficult for me to set properties from the outside of `winit` as long as we use `winit`.
Is there any workaround?

2022-08-05 14:02 UTC, kchibisov commented
You can access it just fine from anywhere, one way is https://docs.rs/winit/0.27.1/x86_64-apple-darwin/winit/platform/macos/trait.WindowExtMacOS.html#tymethod.ns_window.

2022-08-05 17:32 UTC, Matts966 commented
I tried to implement in neovide.
Thank you :)

https://github.com/neovide/neovide/pull/1459

2023-01-15 20:22 UTC, kchibisov commented
Given that feature could be easily added downstream when need. I'd say it's out of scope for winit.

2023-01-15 20:22 UTC, closed without merging