Tidy up "platform-specifc" doc sections
rust-windowing/winit pull request #2356
Opened 2022-07-03 08:41 UTC by maroider

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

This fixes some minor inconsistencies that have been bothering me a bit. This includes `**macOS / X11 / Wayland / Windows:**`-style entries, which I've normalized to the form I just used, as that's what appears to already be used the most.

2022-07-03 09:20 UTC, trimental commented
https://github.com/rust-windowing/winit/blob/1b72bf35cc09dbbe12e355688855b945187b7464/src/event.rs#L375 Probably needs a `## Platform-specific`

2022-07-10 16:03 UTC, kchibisov requested changes

2022-07-10 16:03 UTC, kchibisov commented on bacon.toml
> +# This is a configuration file for the bacon tool
This file should be removed.

2022-07-20 10:43 UTC, kchibisov approved these changes

2022-07-20 11:45 UTC, merged