feat(x11): Add Window::drag_resize_window
rust-windowing/winit pull request #2515
Opened 2022-10-12 20:38 UTC by mmstick

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

Implements functionality required to resolve #725 for X11. Uses the example from #2003. Only supports X11 on Linux for now. Wayland support will require a future release of sctk with the additional protocol added to the API. And there's some substantial changes in sctk at the moment so upgrading this library will be a bit of a chore. Code from #2003 for Windows support could be added on top of this.

2022-10-16 14:51 UTC, aniketbiprojit commented
Winit supports drag_window_resize without any addition in current master on Apple M1. Probably shouldn't panic on drag_window_resize and just give a warning to developers.

https://user-images.githubusercontent.com/24915107/196042176-7879a5d3-9ab6-4b15-9853-e09bc105e7f2.mov

2022-10-16 15:14 UTC, mmstick commented
There isn't a panic in the source code. It is simply stating that it's not supported by winit. This patch only adds support for X11. I don't have a Mac to add support for that.

2022-10-17 06:35 UTC, aniketbiprojit commented
Cool. Just wanted to add that Apple supports this out-of-the-box right now without calling this function.

2022-10-28 21:48 UTC, kchibisov requested changes
You should remove the parts saying that Wayland is impelemented since it's cleary not.

2022-10-28 21:48 UTC, kchibisov commented on src/window.rs
> +    /// immediately before this function is called.
Should add `# Platform-specific` section describing the support and implications.

2022-10-28 21:48 UTC, kchibisov commented on src/platform_impl/linux/wayland/window/mod.rs
> +        self.send_request(WindowRequest::DragResizeWindow(direction));
No need to do this if it's not working anymore.

2022-10-28 22:42 UTC, mmstick commented
Which parts mention that Wayland is supported? I did already update the platform-specific table to only show that X11 is supported.

2022-11-03 17:20 UTC, kchibisov requested changes
Looks fine, just some minor notes.

2022-11-03 17:20 UTC, kchibisov commented on src/platform_impl/linux/wayland/window/mod.rs
> +        // self.send_request(WindowRequest::DragResizeWindow(direction));
```suggestion
```

2022-11-03 17:20 UTC, kchibisov commented on src/platform_impl/linux/x11/window.rs
> +        self.drag_initiate(8) // _NET_WM_MOVERESIZE_MOVE
Could you define this constant with the others below? Could put them into `util.rs`. Could put them into `util/wm.rs`.

2022-11-03 17:20 UTC, kchibisov commented on CHANGELOG.md
> +- On X11, added `drag_resize_window` method
Seems like rebase failed, you should move at the top of the unreleased section.

2022-11-03 18:27 UTC, kchibisov approved these changes

2023-01-11 16:50 UTC, jackpot51 approved these changes

2023-01-11 16:56 UTC, mmstick commented
Rebased with conflicts resolved. The period added to the changelog entry.

2023-01-11 17:07 UTC, merged

2023-01-11 17:13 UTC, kchibisov commented
Thanks, I somehow forgot that this PR existed.