On macOS, add documentEdited APIs
rust-windowing/winit pull request #2550
Opened 2022-11-07 15:53 UTC by amrbashir

Port of https://github.com/tauri-apps/tao/commit/33fdeab6291d4aef8ea9facb58fe9583f6c1aaf3

- [ ] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2022-11-20 13:02 UTC, kchibisov commented
How does it work? Is it basically enable/disable prompt and there's no event attached to it that says that user is trying to close the window with edit? Do you get `CloseRequested` in that case?

Is that to prevent force close by the system, since winit app can ignore `CloseRequested` and emulate the dialog thingy?

2022-11-20 13:42 UTC, amrbashir commented
I don't use macOS but I think it is just a hint to the user that this window has unsaved changes, see this image 
![image](https://user-images.githubusercontent.com/48618675/202905452-ed58a70a-bdba-4344-bef8-2d962fa11486.png)

2022-11-22 22:20 UTC, madsmtm requested changes
Tested it, it has no effect on `CloseRequested`, is simply a visual indication (though that would be nice to document!). It looks as follows on macOS 10.14.6:

Normal:
<img width="128" alt="unedited" src="https://user-images.githubusercontent.com/10577181/203432792-e1acb650-4b25-457a-a31c-3d66c0048aae.png">

Edited:
<img width="131" alt="edited" src="https://user-images.githubusercontent.com/10577181/203432789-8de3f5b1-8469-4e15-b095-1d5a0535fd08.png">

2022-11-22 22:20 UTC, madsmtm commented on src/platform/macos.rs
> +    fn set_decoument_edited(&self, edited: bool);
Typo
```suggestion
    fn set_document_edited(&self, edited: bool);
```

2022-11-22 22:20 UTC, madsmtm commented on src/platform/macos.rs
> +    /// Get the window's edit state.
Would be nice to document how this relates to `CloseRequested`, something like:
```suggestion
    /// Get the window's edit state.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// WindowEvent::CloseRequested => {
    ///     if window.is_document_edited() {
    ///         // Show the user a save pop-up or similar
    ///     } else {
    ///         // Close the window
    ///         drop(window);
    ///     }
    /// }
    /// ```
```

2022-11-23 13:15 UTC, madsmtm approved these changes
Thanks, will merge in a few hours once CI catches up

2022-11-23 15:07 UTC, merged