On Windows, fix window size for maximized, undecorated windows
rust-windowing/winit pull request #2584
Opened 2022-12-06 17:31 UTC by msiglreith

Mostly takes the relevant pieces from https://github.com/rust-windowing/winit/pull/1891 regarding max window handling which haven't been included so far.
Attributed @amrbashir in the commit accordingly, I hope that's fine!

Fixes https://github.com/rust-windowing/winit/issues/2568

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2022-12-06 17:48 UTC, amrbashir requested changes
Thank you for the attribution, unfortunately a bug with this code came to light since then, see below.

2022-12-06 17:48 UTC, amrbashir commented on src/platform_impl/windows/event_loop.rs
> +                let monitor = monitor::current_monitor(window);
using `monitor::current_monitor` which uses `MonitorFromWindow` and `MONITOR_DEFAULTTONEAREST` is unreliable in this situation, see https://github.com/MicrosoftEdge/WebView2Feedback/issues/2549#issuecomment-1180843867, instead, `MonitorFromRect` should be used

2023-01-27 04:41 UTC, kchibisov commented
@msiglreith is this good to go?

2023-01-27 12:09 UTC, msiglreith commented
not yet, I will update it today

2023-01-28 13:04 UTC, merged