On web, allow recreating event loop when using `spawn`
rust-windowing/winit pull request #2720
Opened 2023-03-06 18:48 UTC by grovesNL

- [X] Tested on all platforms changed
- [X] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

As described in https://github.com/rust-windowing/winit/pull/2344#issuecomment-1176763837, it's useful to be able to recreate event loops on the web when using `spawn`, since the wasm module remains loaded. e.g., switching between tabs on a single page app and recreating a canvas doesn't currently work without some kind of workaround like this.

This won't change the behavior of `run`, so that will still panic when attempting to create multiple event loops.

I know there are probably still closures leaked when using this approach but don't expect this to be an issue in practice. We can also deal with any leaked closures later. At least anecdotally I've been using this approach for a while now and haven't run into any problems.

2023-03-06 19:50 UTC, grovesNL commented
cc @kchibisov this is the approach you mentioned on https://github.com/rust-windowing/winit/pull/2344#issuecomment-1176763837

2023-03-11 13:26 UTC, kchibisov requested changes
I think that's not exactly what I've suggested.

What I meant was more like `.with_allow_multiple_loops(true)` in the new `EventLoopBuilderExtWeb`.

Can't you create multiple event loops at once on the web and then use `spawn`? If you can't and you must use `spawn` before creating the second loop, then it should be static in a comment.

You should also update the docs for the `spawn` that it allows multiple event loop creation.

Though, I guess you can't have 2 loops before spawn, since you need to consume the loop?

2023-03-11 14:12 UTC, grovesNL commented
I'd be happy to change the approach here but I'm not sure I follow the approach you described.

In case the use case isn't clear, my use case works like this:
- the wasm module is loaded
- spawn/the event loop is created once and sets the static flag
- some action in the application causes the event loop and canvas are destroyed – basically all state is destroyed except for statics because they're shared at the wasm module level
- some action in the application triggers a new spawn/event loop creation, which fails because of the static flag

The flow works the same way as run/spawn normally would, except I need to clear the static flag that's set at the wasm module level because it prevents run/spawn from being called again. I'm not trying to run multiple event loops simultaneously or similar.

2023-03-11 14:16 UTC, kchibisov commented
No, what I mean is could you do something like that on wasm

```rust
let evl1 = EventLoop::new();
let evl2 = EventLoop::new();
// And spawn later on.
```

Right now you won't be able to do so, because you clear only on spawn.

What I suggested is that once you build you pass inside the builder a flag that you must not restrict additional creation, so instead of clearing on `spawn` you won't set the static global at all.

2023-03-13 02:17 UTC, grovesNL commented
Sure, we could do that instead. I don't have a strong preference though it feels like we should just handle it internally instead of having it be opt-in on the builder. Is it valid to recreate the event loop multiple times without consuming it in run/spawn?

2023-03-13 03:02 UTC, kchibisov commented
>Is it valid to recreate the event loop multiple times without consuming it in run/spawn?

Not on any other platform, buy maybe you can do that on Wasm? That's what I'm asking you, if you can create multiple events loop at the same time on wasm, we should allow that with the extension to the builder, on any other platform it's impossible.

2023-03-13 11:21 UTC, daxpedda commented
> That's what I'm asking you, if you can create multiple events loop at the same time on wasm, we should allow that with the extension to the builder

I don't think this is possible in Winit, there are event handlers registered on the window itself, like the scale change observer, which would be overwritten by a new event loop.

It's possible to augment these event handlers to handle multiple event loops, but I don't think that's the goal here.

2023-03-13 12:28 UTC, kchibisov requested changes

2023-03-13 12:28 UTC, kchibisov commented on src/event_loop.rs
> +    #[cfg(target_arch = "wasm32")]
```suggestion
    #[cfg(wasm_platform)]
```

2023-03-13 12:28 UTC, kchibisov commented on src/event_loop.rs
> +static EVENT_LOOP_CREATED: OnceCell<Mutex<bool>> = OnceCell::new();
Shouldn't we refactor that to `AtomicBool` or simply `Mutex` given that it could be changed now? The `Mutex` is const anyway now.

2023-03-13 12:28 UTC, kchibisov commented on CHANGELOG.md
> +- On web, allow event loops to be recreated with `spawn`.
```suggestion
- On Web, allow `EventLoop` to be recreated after using `spawn`.
```

2023-03-13 12:28 UTC, kchibisov commented on src/platform_impl/web/event_loop/mod.rs
> +    pub fn spawn<F>(self, event_handler: F)
Could you update the `spawn` docs on the `trait` wrt new behavior change?

2023-03-13 12:28 UTC, kchibisov commented
>I don't think this is possible in Winit, there are event handlers registered on the window itself, like the scale change observer, which would be overwritten by a new event loop.

Thanks, that's what I wanted to know.

2023-03-13 13:50 UTC, notgull commented
Wouldn't it be possible to avoid resetting the event handlers by using `addEventListener` instead of setting them?

2023-03-15 02:37 UTC, grovesNL commented
Thank you for the review! I think everything should be addressed now.

I don't think it's worth trying to support multiple event loops right now (at least to solve this immediate issue) since it opens up a lot of other questions about how we might want to extend support for the web in general. For example:
- Should we allow multiple windows (canvases) each having their own event loop or should they share one event loop?
- Are we confident that all of the event handlers/CSS queries are set up correctly to support multiple event loops instead of setting a single event loop as the listener?
- How do multiple event loops interact with web workers and offscreen canvases?

I'd be happy to consider ways we could extend this later on, but the current change feels like a simple enough that we could land initially.

2023-03-15 12:52 UTC, daxpedda approved these changes
LGTM.

I think we shouldn't try to support multiple event loops until we know what a use-case for this even looks like, in any case I agree with @grovesNL this is out-of-scope for this PR.

2023-05-28 21:02 UTC, daxpedda commented
@grovesNL I'm happy to merge this after a rebase.

2023-06-17 15:04 UTC, daxpedda commented
I'm gonna close this as it's rather old now and needs a rebase.
Feel free to reopen after a rebase.

In general this issue is tracked in #2885.

2023-06-17 15:04 UTC, closed without merging

2024-04-28 15:22 UTC, arximboldi commented
I really wish this was merged. Any chance @grovesNL to reactivate this?