Add support of using custom image as cursor icon on windows
rust-windowing/winit pull request #2833
Opened 2023-06-01 10:53 UTC by Icemic

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

Adds a `Window::set_cursor_custom_icon` method, which we can pass an `Icon` to. And this icon is sightly different from a icon created by `Icon::from_rgba`, because it lacks of hotspot infomation (default to the center of image in fact), so I add an `Icon::from_rgba_cursor` which has extra hotspot parameters.

A custom cursor icon has higher priority than system cursor once it is set (when processing WM_SETCURSOR). And custom cursor icon will be dropped if `Window::set_cursor_icon` is called again.

This feature is only added to Windows platform for now, and `.cur` or `.ani` format is also not supported for potential cross-platform requirements.

Maybe a common `Cursor` struct should be added instead of reusing `Icon`, but on Windows an icon or cursor is not strictly differentiated and I haven't delved into the api of other platforms yet. So I just make minimal changes.

2023-06-03 22:27 UTC, msiglreith requested changes
Thanks!

I would prefer a dedicated cusor type, where to user can create cursor with a standard icon or with a custom one. At least on X11 IIRC the cursor and icons are different types and mixing them will lead to issues. This would also help to keep a single entry point for the setting the cursor.

2023-06-04 05:14 UTC, madsmtm reviewed
> I would prefer a dedicated cusor type, where to user can create cursor with a standard icon or with a custom one. At least on X11 IIRC the cursor and icons are different types and mixing them will lead to issues. This would also help to keep a single entry point for the setting the cursor.

Fully agree, custom cursors are also supportable on macOS and web, both of which define `PlatformIcon` as `NoIcon`.

We should also consider how this will interact with the `cursor-icon` crate.

2023-06-04 20:54 UTC, kchibisov commented
Yeah, we might add a variant to `cursor-icon` crate with the custom cursor image. I'd assume some `ARGB` variant should be fine.

2023-06-05 06:16 UTC, madsmtm commented
`cursor_icon::CursorIcon` is `Copy`, so that may be difficult, and perhaps not desired either? There is value in keeping that crate clean of cludges / additions like this.

Instead, we could do something like this (in `winit`):
```rust
// Bikeshed names
pub struct CustomCursorRGBA { ... }
pub struct CustomCursorURL { ... }

trait CursorIconTrait: Sealed { ... }

impl CursorIconTrait for cursor_icon::CursorIcon { ... }
impl CursorIconTrait for CustomCursorRGBA { ... }
impl CursorIconTrait for CustomCursorURL { ... }

impl Window {
    fn set_cursor_icon(&self, icon: impl CursorIconTrait) { ... }
}

//
// Or alternatively:
//

// Bikeshed name
#[non_exhaustive]
pub enum CursorIconEnum {
    Standard(cursor_icon::CursorIcon),
    CustomRGBA(...),
    // E.g. for web
    CustomURL(Url),
}

impl From<cursor_icon::CursorIcon> for CursorIconEnum { ... }
impl From<...> for CursorIconEnum { ... }
impl From<Url> for CursorIconEnum { ... }

impl Window {
    fn set_cursor_icon(&self, icon: impl Into<CursorIconEnum>) { ... }
}
```

2023-06-15 17:05 UTC, kchibisov commented
I could add that on Wayland you simply provide and RGBA buffer because you draw the cursor. The animation is also done by you or by compositor, when using named cursors.

2023-12-15 13:00 UTC, daxpedda commented
@Icemic we currently have a fully working implementation in https://github.com/rust-windowing/winit/pull/3218 for all backends which went through quite a bit of design work already.

Feel free to drop a review for the Windows backend :)

2023-12-17 02:08 UTC, madsmtm commented
Superceded by https://github.com/rust-windowing/winit/pull/3218

2023-12-17 02:08 UTC, closed without merging