Implement X11 extensions using x11rb instead of Xlib
rust-windowing/winit pull request #2968
Opened 2023-07-21 19:52 UTC by notgull

- [ ] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

Ports the code for the XInput and XRandr to use `x11rb` instead of Xlib.

Draft because there's still more to do, and also I seem to have broken raw event inputs.

2023-07-21 22:54 UTC, notgull commented
Weirdly, it looks like device handling is pretty tightly kneaded into Xlib's event handling, so I can't take it out until #2767 merges. So I guess what's here is what's here.

2023-07-22 11:40 UTC, kchibisov requested changes
Could we have a one commit per extension change? So XRandr and Xinput separatelly?

2023-08-27 14:37 UTC, kchibisov requested changes

2023-08-27 14:37 UTC, kchibisov commented on src/platform_impl/linux/mod.rs
>                  Some(primary_monitor)
Bum, can you bump to none on `except` failure?

2023-08-27 14:37 UTC, kchibisov commented on src/platform_impl/linux/x11/mod.rs
> +            .expect("Failed to query XInput2 extension")
```suggestion
            .expect("Failed to query XInput extension")
```

2023-08-27 14:37 UTC, kchibisov commented on src/platform_impl/linux/x11/mod.rs
> +const ALL_MASTER_DEVICES: u16 = 1;
Could you move them to the top of the file?

2023-08-29 20:57 UTC, kchibisov approved these changes

2023-08-29 21:01 UTC, merged