On Windows, set name of Window Class, closes #2977
rust-windowing/winit pull request #2978
Opened 2023-07-25 16:15 UTC by geraudloup

allow to customize it instead of current value hard coded "Window Class"

- [X] Tested on all platforms changed
- [X] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [X] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [X] Created or updated an example program if it would help users understand this functionality
- [X] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2023-07-28 16:47 UTC, madsmtm commented
Linking your related issue: https://github.com/rust-windowing/winit/pull/2978

2023-07-28 17:23 UTC, msiglreith requested changes
thanks for the pull request!
I would request a few smaller changes, otherwise looks fine to me

2023-07-28 17:23 UTC, msiglreith commented on CHANGELOG.md
> +- On Windows, added `WindowBuilderExtWindows::with_window_classname` and changed the `register_window_class` definition and call in `init` to use newly defined Windows Platform Attribute `window_clas
```suggestion
- On Windows, added `WindowBuilderExtWindows::with_class_name` to customize the internal class name.
```

2023-07-28 17:23 UTC, msiglreith commented on src/platform/windows.rs
> +    fn with_window_classname<S: Into<String>>(self, classname: S) -> WindowBuilder;
let's just call it `with_class_name` and adjust the attribute name as well.

2023-07-28 17:23 UTC, msiglreith commented on src/platform_impl/windows/window.rs
> +    let class_name = register_window_class::<T>(&pl_attribs.window_classname);
```suggestion
    let class_name = util::encode_wide(&pl_attribs.class_name);
    register_window_class::<T>(&class_name);
```

2023-07-28 17:23 UTC, msiglreith commented on src/platform_impl/windows/window.rs
> +unsafe fn register_window_class<T: 'static>(window_classname: &String) -> Vec<u16> {
With the change suggested above we can simplify it a bit to
```suggestion
unsafe fn register_window_class<T: 'static>(class_name: &[u16]) {
```

2023-07-29 13:04 UTC, msiglreith commented on FEATURES.md
> +* Setting the name of the Window Class used When creating the window
```suggestion
* Setting the name of the internal window class
```

2023-07-29 13:05 UTC, msiglreith approved these changes

2023-07-29 13:39 UTC, merged

2023-08-08 14:33 UTC, daxpedda commented
Some additional documentation on what a "Window Class" is and what it's used for would be nice.