WIP on improving CI (build times)
rust-windowing/winit pull request #2988
Opened 2023-07-30 21:21 UTC by madsmtm

Replaces https://github.com/rust-windowing/winit/pull/2211.

- [ ] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2023-07-31 00:25 UTC, madsmtm commented
I'd estimate the build got on average 2 minutes faster (10 mins -> 8 mins) (depending on time of day and amount of concurrent builds)

2023-08-03 15:14 UTC, kchibisov requested changes
The changes are not equivalent to what we had before, in particular, features are not respected (I don't see them on CI jobs for example). Verbose was removed in some places. And the CI itself is much more complicated now, though, if it's faster than it's fine...

2023-08-03 22:27 UTC, madsmtm commented on .github/workflows/ci.yml
> +      run: cargo doc --no-deps $OPTIONS --document-private-items
I... Intended to fold that into `$OPTIONS`, but it seems I made a mistake along the way

2023-08-03 22:28 UTC, madsmtm commented on .github/workflows/ci.yml
> +      run: cargo fmt -- --check
I'm pretty sure the `--all` argument is redundant, that's what happens by default? But let me check first

2023-08-04 02:15 UTC, kchibisov commented on .github/workflows/ci.yml
> +      run: cargo fmt -- --check
I don't think it formats examples?

2023-08-04 14:51 UTC, madsmtm commented on .github/workflows/ci.yml
> +      run: cargo doc --no-deps $OPTIONS --document-private-items
Nvmd, this works as intended; `$OPTIONS` now contains the features as well

2023-08-04 14:51 UTC, madsmtm commented on .github/workflows/ci.yml
> +      run: cargo fmt -- --check
Documentation for `--all`:
> Format all packages, and also their local path-based dependencies

But from a quick test `cargo fmt` by itself formats examples and the `run-wasm` crate.

2023-08-04 14:54 UTC, madsmtm commented
The features are folded into `$OPTIONS`, and the `CARGO_TERM_VERBOSE: true` makes everything run in verbose mode.

I do agree about the complexity, unfortunate but difficult to do otherwise without committing `Cargo.lock`.

2023-08-24 20:16 UTC, madsmtm commented
I believe I've resolved the outstanding concerns, so I'll merge this fairly soon unless there are others?

2023-08-27 14:03 UTC, kchibisov commented
@madsmtm what's the reason CI is not being fully run? I don't want to merge a patch that changes CI which can't run everything on the CI itself.

2023-08-27 14:12 UTC, madsmtm commented
It's because of the [branch protection rule](https://github.com/rust-windowing/winit/settings/branch_protection_rules/5589098); I intended to change that before I merged, but only just before

2023-08-27 14:17 UTC, kchibisov commented
Ah, those are leftover tasks? We could merge and then change what is required.

2023-08-27 14:19 UTC, madsmtm commented
Exactly

2023-08-27 14:23 UTC, kchibisov approved these changes

2023-08-27 14:25 UTC, merged