Custom cursor icon support
rust-windowing/winit pull request #3039
Opened 2023-08-22 15:58 UTC by valaphee

- [ ] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

One possible solution for https://github.com/rust-windowing/winit/issues/3005, adds a way to set custom icons in winit using the existing `Window::set_cursor_icon` method.

At the moment this is only a draft, because not all major platforms are implemented/tested
- [ ] iOS
- [ ] X11
- [ ] Wayland
- [ ] MacOS
- [ ] Web
- [x] Windows

I can't really test for Apple platforms because I don't own Apple devices.

2023-08-22 16:24 UTC, kchibisov requested changes
I'm not sure that reusing `Icon` is a good idea, how does it map to the cursor icon used on the platforms? I'm interested wrt macOS/Web/Windows, since X11/Wayland use just argb/xrgb buffers for all of that.

Also, without hotspot it's all kind of useless.

2023-08-22 16:24 UTC, kchibisov commented
Also, see https://github.com/rust-windowing/winit/pull/2833/files

2023-08-22 18:20 UTC, valaphee commented
For web: you would have to use css and the "cursor" property, where you can specify a url, which can also be an base64 string, containing the png encoded cursor, but this is already how it works, its just a question of encoding the icon (rgba) to png and packing it into base64, (or ico because there its possible to specify the hotspot)

For iOS: NSCursor has an instance method called initWithImage with NSImage and hotSpot, this would suggest Icon being of type NSImage, but cursor icon doesn't seem to implemented there? `debug!("`Window::set_cursor_icon` ignored on iOS")`

Good point, didn't thought about hotspot, I would add it to CursorIcon::Custom

2023-08-23 14:53 UTC, daxpedda requested changes
This isn't really feasible for Web like this.

Firstly `PlatformIcon` has to be split, because it's currently used for both cursor and window, in the case of Web window needs to continue using `NoIcon` but cursor now requires `RgbaIcon`.

Secondly adding the `image` dependency is overkill. I would argue that Web should support links before it starts supporting raw RGBA in the first place anyway. If we really want to support RGBA on Web then we should either use the `png` crate directly or use the WebAPI to do the conversion: `ImageData` -> `ImageBitmap` -> `Canvas` -> data URL.

Adding platform-specific formats shouldn't be a problem as they go through methods on `Icon` anyway.

2023-08-28 11:38 UTC, valaphee commented
I definitely agree with the image crate being overkill, and I'll split up Icon (as normal icons also don't need the hotspot property).

Using urls could definitely be an option, and for RGBA, I'll take a look into utilizing the web api.

2023-09-24 21:57 UTC, valaphee commented
Split-up Icon and CustomCursorIcon pub import, and switched to png crate, web also doesn't use RgbaImage and instead just the url repr.

2023-09-25 08:31 UTC, daxpedda commented on src/icon.rs
> +        Self::from_rgba_with_hotspot(rgba, width, height, width / 2, height / 2)
```suggestion
        Self::from_rgba_with_hotspot(rgba, width, height, 0, 0)
```
Shouldn't the default be the top-left corner?

2023-09-25 08:35 UTC, daxpedda commented on src/platform_impl/web/icon.rs
I believe this is the kinda stuff that goes into `src/platform/web.rs`.

2023-09-25 08:36 UTC, daxpedda commented on src/platform_impl/web/icon.rs
> +    pub fn from_url(url: &str, hotspot_x: u32, hotspot_y: u32) -> Self {
Can we add a `with_hotspot()` alternative here?

2023-09-25 08:37 UTC, daxpedda commented on src/platform_impl/web/mod.rs
>  pub(crate) use crate::icon::NoIcon as PlatformIcon;
```suggestion
```

2023-09-25 13:20 UTC, valaphee commented on src/platform_impl/web/icon.rs
The platform-specific implementation at least for Windows is in the `platform_impl` module, and they are exposed in `platform`, by extending Icon

Basically just copied it from there

2023-12-17 02:08 UTC, madsmtm commented
Superseded by https://github.com/rust-windowing/winit/pull/3218

2023-12-17 02:08 UTC, closed without merging