Fix WaitUntil on X11
rust-windowing/winit pull request #3091
Opened 2023-09-09 21:14 UTC by Riateche

It seems that WaitUntil is currently broken on X11: no events are received when the timer expires, unless there is an actual window event. This issue seems to be introduced in c47d08. This PR adds an additional condition to the spurious wake up check, recognizing ResumeTimeReached as a valid cause to wake up.

- [ ] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2023-09-10 20:52 UTC, notgull approved these changes
Looks good to me!

2023-09-16 10:26 UTC, kchibisov requested changes
Could you add a changelog entry for this one?

2023-09-17 09:36 UTC, StarStarJ commented
I am currently testing the new changes and noticed this bug too. However in my case I was using poll
```rs
event_loop.set_control_flow(winit::event_loop::ControlFlow::Poll)
```

despite the description, the loop did not run the whole time

Additionally to this patch i added a
```rs
| StartCause::Poll
```

to the `matches!` call
which seem to have fixed it.

I only tested this with x11. So I don't know if this affects other backends too

2023-09-17 09:44 UTC, kchibisov commented on src/platform_impl/linux/x11/mod.rs
> +        }
```suggestion
        // False positive / spurious wake ups could lead to us spamming
        // redundant iterations of the event loop with no new events to
        // dispatch.
        //
        // If there's no readable event source then we just double check if we
        // have any pending `_receiver` events and if not we return without
        // running a loop iteration.
        // If we don't have any pending `_receiver`
        if !self.has_pending() && !matches!(&cause, StartCause::ResumeTimeReached { .. } | StartCause::Poll)
        {
            return;
        }
```

2023-09-17 09:45 UTC, kchibisov commented on src/platform_impl/linux/x11/mod.rs
> +        }
I think it should be like that, actually. The readiness check seems arbitrary given that we have other sources of events, and X11 readiness has nothing to do with them.

2023-09-17 23:05 UTC, Riateche commented
I've added a changelog entry.

2023-09-20 11:14 UTC, kchibisov approved these changes

2023-09-20 11:15 UTC, merged

2023-09-20 11:15 UTC, kchibisov commented
Thank you!