Cache the XRandR extension version
rust-windowing/winit pull request #3337
Opened 2023-12-29 04:35 UTC by notgull

Maybe this will fix #3355

- [ ] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2023-12-29 07:17 UTC, notgull commented
This doesn't look like it fixes the issue, but it's probably good to do anyways

2023-12-29 16:13 UTC, kchibisov commented
Do we need this?

2023-12-29 16:20 UTC, notgull commented
It's probably nice to have. But I need to rebase it first

2023-12-29 17:30 UTC, kchibisov requested changes

2023-12-29 17:30 UTC, kchibisov commented on CHANGELOG.md
> +
```suggestion
```

2023-12-29 17:30 UTC, kchibisov commented on CHANGELOG.md
> +- Cache the XRandR version before calling `available_monitors()`.
Not relevant, since the other entry kind of accounts for it already.

```suggestion
```

2023-12-30 06:03 UTC, kchibisov approved these changes

2023-12-30 06:04 UTC, merged