Android: allow EventLoop recreation
rust-windowing/winit pull request #3353
Opened 2024-01-03 12:23 UTC by SnowyCoder

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

I've added this as the default behavior because it's what is expected in android when you call `event_loop.exit()` and reopening the activity, is it better suited for a sort of `EventLoopBuilderExtAndroid`?

Closes #3325

2024-10-16 08:23 UTC, MarijnS95 requested changes
Simply allowing recreation hides a poor design decision to not fix how `winit` and its auxiliary crates mismanage Android's `Activity` Lifecycle, even in the probably close to ~4th refactor of the Android backend with the introduction of the `android-activity` crate. Despite multiple requests to tackle this problem from the get-go, which is expected to have far-stretching effects on the rest of the implementation, it has been ignored on every refactor.

The issue and a simplified solution (tl;dr: move towards handling the `Activity` lifecycle appropriately) is better described in https://github.com/rust-windowing/winit/issues/3325#issuecomment-1879742860.

Since this PR proposes a workaround in the opposite direction by papering over the issue rather than solving towards it, and above all fails to explain `"Due to android platform-specific behaviour"` what the actual problem is _nor any of the drawbacks that this workaround is causing_, I think we should close this PR and work towards implementing my proposed changes from the bottom up.

2024-10-16 09:26 UTC, closed without merging

2024-10-16 09:26 UTC, daxpedda commented
Agreed.

2024-10-17 08:33 UTC, SnowyCoder commented
Sorry for the trouble, I created this Pull Request to propose a possible solution before discussing the proper solution and before receiving the mentioned comment.
I no longer have the time required to help write a real solution.

2024-10-17 08:47 UTC, MarijnS95 commented
No worries at all, we're just closing this (as said) to communicate that this is not the direction we want nor are planning to head into.

We don't need any help writing a solution, changes for that are already in progress by the respective winit and/or Android maintainers.