On Windows, buffer `ScaleFactorChanged` new size if window is maximized
rust-windowing/winit pull request #3408
Opened 2024-01-18 20:43 UTC by amrbashir

This fixes an issue when setting the position of the window on a new monitor and immediately maximizing it

```rs
window.set_outer_position::<PhysicalPosition<u32>>((2000, 200).into());
window.set_maximized(true);
```

Due to the nature of the event loop, the requested position and maximization state will apply correctly but due to the fact that the new position is a different monitor, a `ScaleFactorChanged` is emitted afterwards to the evenloop and a new size is set while the window is still maximized which results in a window that has `WS_MAXIMZE` window style but doesn't cover the whole monitor.

Screenshot:
![image](https://github.com/rust-windowing/winit/assets/48618675/0ce2b0bb-5f85-4e06-bf1d-025169eaa51a)

- [X] Tested on all platforms changed
- [X] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [X] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [X] Created or updated an example program if it would help users understand this functionality
- [X] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2024-02-01 03:24 UTC, notgull approved these changes
Thanks!

Poke @Stefyn, could I convince you to take a look at this?

2024-02-01 13:22 UTC, msiglreith commented
small note: as I have a 2nd monitor now I planned to review it at the weekend

2024-02-04 12:24 UTC, msiglreith requested changes
Thanks, but I don't like the additional state tracking and logic for handling a specific edge case. Other cases like move + `request_inner_size` will also see similar inconsistent behavior due to retroactively applying outdated size changes.

I would prefer to only apply changes from a buffer `ScaleFactorChanged` if the user explicitly updated the size. Therefore just call `set_size` when `new size != old size` as the original size change has already been applied.

2024-02-05 23:27 UTC, amrbashir commented
Hopefully this is what you meant.

2024-02-06 19:35 UTC, msiglreith commented on CHANGELOG.md
> +- On Windows, apply `ScaleFactorChanged` changes only if user new size is different than what the OS reporeted, which fixes and issue when moving a window to another monitor and immediately maximizin
```suggestion
- On Windows, fix inconsistent resizing behavior with multi-monitor setups when repositioning outside the event loop.
```

2024-02-06 19:46 UTC, merged

2024-02-07 00:50 UTC, kchibisov commented
Next time could you _please_ properly format commits before merging?