On Windows, Remove `WS_CAPTION`, `WS_BORDER` and `WS_EX_WINDOWEDGE` styles for child windows
rust-windowing/winit pull request #3410
Opened 2024-01-19 01:51 UTC by amrbashir

closes #2754

- [ ] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2024-01-19 12:16 UTC, msiglreith requested changes
Thanks but this should only affect undecorated windows

2024-01-20 01:05 UTC, amrbashir commented
Should be good to go now

2024-01-20 12:06 UTC, msiglreith approved these changes

2024-01-20 12:07 UTC, merged

2024-01-27 21:06 UTC, ArthurKlausHoff commented
Why WS_CAPTION, WS_BORDER and WS_EX_WINDOWEDGE are only removed from child windows?

This won't change anything if a non-child window doesn't have decorations, they're still broken.