Bump build dependency `cfg_aliases` to 0.2
rust-windowing/winit pull request #3436
Opened 2024-01-27 10:11 UTC by waywardmonkeys

- [x] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2024-01-27 12:13 UTC, kchibisov requested changes
Always specify full latest version available at the time of submitting the patch.

2024-01-27 12:13 UTC, kchibisov commented on Cargo.toml
> +cfg_aliases = "0.2"
```suggestion
cfg_aliases = "0.2.0"
```

2024-01-27 13:56 UTC, waywardmonkeys commented
@kchibisov Updated!

2024-01-29 17:27 UTC, merged

2024-01-29 17:27 UTC, kchibisov commented
Thanks.