Split out platform-independent types into a new winit-core crate
rust-windowing/winit pull request #3455
Opened 2024-02-05 00:02 UTC by notgull

This PR implements the first item of #3433 by splitting the platform-independent types from `winit` into a new crate: `winit-core`. It contains mostly types, traits and structures from `winit` that are platform independent. As part of this commit, I made a handful of changes to certain types (most notably `Event`) to make them more platform-independent.

A brief summary of the changes made:

- `dpi` and `keyboard` modules are copied over wholesale.
- The errors in the `error` module that don't involve `OsError` are copied as well.
- Some types from the `window` module are copied verbatim. `WindowId` is now a newtype over `u64` instead of a platform-specific value. `ActivationToken` is copied and given methods to make it useful.
- `Event` is given a new generic parameter to describe platform-specific key information. `InnerSizeWriter` is given methods to allow for instantiation. Aside from this, most things from the `event` module are copied verbatim.
- `AsyncRequestSerial` and `ControlFlow` are copied from `event_loop`. `AsyncRequestSerial::get` is made public.

Aside from this, the biggest changes are just moving everything to `winit-core` and then re-exporting it.

I've formatted this PR as a series of changes in order to make reviewing easier. @rust-windowing/winit Please review this PR quickly. It will be difficult to rebase on top of new changes and it'll take me the whole day to remake it.

Closes #2759

- [ ] Tested on all platforms changed
  - [x] Ran `cargo check` on all platforms to make sure it builds there.
  - [ ] Did not actually run example programs on all platforms.
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2024-02-05 00:19 UTC, notgull commented
@jackpot51 Any insight into why the Redox CI is failing with `__errno not found` errors?

2024-02-05 00:25 UTC, jackpot51 commented
@notgull not sure, it may be trying to compile with the host compiler instead of a cross compiler?

2024-02-05 00:33 UTC, notgull commented
It appears that the only failures are the Redox failure (is that new?) and what appears to be a bug in `cargo-apk`. Both of which are unrelated to this PR.

2024-02-05 04:20 UTC, notgull commented
No, the Redox failure is new. It looks like Redox can't compile `run-wasm`.

2024-02-05 04:25 UTC, kchibisov commented
Why it compiles it in the first place?

2024-02-05 05:05 UTC, notgull commented
> Why it compiles it in the first place?

Because with the new workspace layout it tries to compile everything instead of just `winit`

2024-02-12 17:40 UTC, madsmtm requested changes

2024-02-12 17:40 UTC, madsmtm commented on winit/src/platform_impl/ios/mod.rs
> -/// other pointer device that caused a touch event).
I'd like to retain this comment in some shape or form, it is nice to know that device IDs will never be supported on iOS.

2024-02-12 17:40 UTC, madsmtm commented on winit-core/src/event.rs
> +pub struct KeyEvent<Extra> {
I dislike this design, and think we need to discuss further how to do this sort of thing. See also https://github.com/rust-windowing/winit/issues/3064.

2024-02-12 17:40 UTC, madsmtm commented on Cargo.toml
> +    "winit",
I think it's a mistake to move `winit` to a subdirectory, at least yet, and it also complicates this PR unnecessarily. There is especially value in having the top-level `examples` directory. Let's use the [`include`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) field instead to specify which files should be included in the `winit `package.

2024-02-29 05:23 UTC, closed without merging