Add issue templates
rust-windowing/winit pull request #3483
Opened 2024-02-09 21:14 UTC by madsmtm

Add issue templates, in particular issue templates for each platform, such that we don't have to request the same information each time a new issue is opened.

You can see how it currently looks [over at my fork](https://github.com/madsmtm/winit/issues/new/choose).

I would like feedback on what each platform would like to request from the user. Feel free to edit this PR description.
- [x] macOS: `sw_vers`.
- [ ] Wayland: Compositor? A checkbox to ensure that users know that wayland doesn't show windows unless you draw to them? @kchibisov
- [ ] X11: ? @kchibisov @notgull
- [ ] Windows: Windows build number? Output of `ver`? @msiglreith @maroider
- [ ] Web: Tested browsers? Also versions of these? @daxpedda
- [x] iOS: iOS version, device name.
- [ ] Android: Android version? Is something like `Android 13` descriptive enough, or do you need more? Device information? @MarijnS95 @rib

TODO:
- Add "Feature request", or maybe just "Blank issue" template.

2024-02-23 14:13 UTC, kchibisov requested changes
I also need **untruncated** `WAYLAND_DEBUG=1` log during the bug being reproduced.

2024-02-23 14:13 UTC, kchibisov commented on .github/ISSUE_TEMPLATE/bug_wayland.yml
> +        - label: I understand that windows aren't shown on Wayland unless you draw to them.
```suggestion
        - label: I understand that windows aren't shown on Wayland unless I draw and present.
```

2024-02-23 14:14 UTC, kchibisov commented
On X11 we basically need: window manager, operating system. Not sure if there's anything special.

2024-02-28 19:55 UTC, kchibisov requested changes
Should update to the latest version of winit, but other than that looks good.

2024-03-01 09:48 UTC, kchibisov approved these changes
Not sure about directing to matrix, but maybe it's fine.

2024-03-07 14:04 UTC, kchibisov commented
@daxpedda beep.

2024-03-07 16:00 UTC, daxpedda approved these changes
Apologies for the delay.
Small nit, otherwise LGTM.

2024-03-07 16:00 UTC, daxpedda commented on .github/ISSUE_TEMPLATE/bug_web.yml
> +        - Safari (old than listed)
I think we should remove this because we don't support Safari below v13.

2024-03-15 07:32 UTC, daxpedda approved these changes

2024-03-15 14:15 UTC, merged