Add `LogicalPoint`, `PhysicalPoint` and `Point`
rust-windowing/winit pull request #3529
Opened 2024-02-26 23:28 UTC by amrbashir

part of #2395

- [ ] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2024-02-28 14:34 UTC, daxpedda commented
Looking at #2395 I don't really follow what the motivation here is exactly.
Is there some previous related discussion?

2024-02-28 15:41 UTC, daxpedda commented
My question is specifically how does `Logical/PhysicalPoint` relate to that? Why can that not be done with the types we have now?

2024-02-28 15:44 UTC, daxpedda commented
Ah, I see, thank you!

2024-02-28 20:13 UTC, kchibisov requested changes
Should probably update the docs in `### Position and Size types` with the point stuff.

2024-02-28 20:13 UTC, kchibisov commented
Besides.

@amrbashir given that you had an interest in such crate in the first place, how you deal with e.g. rounding? For example in winit we have special rounding rules on Wayland, because it's rounding is a bit special, but maybe we should define such things in this crate as well, so the `to_logical/to_physical` will account for rounding and make the default like it was before?

2024-02-28 23:00 UTC, amrbashir commented
We didn't give it much thought, since our windows and macOS backend were forked from `winit` and the current behavior of `to_logical/to_physical` have been working fine for us.

2024-02-28 23:03 UTC, amrbashir commented
I just realized that the naming `Point` might be confusing when used with width/height as it conveys position than a dimension, maybe it should be renamed to `LogicalUnit`, `PhysicalUnit` and `Unit` or `PixelUnit` ?

2024-02-29 05:50 UTC, kchibisov commented
>I just realized that the naming Point might be confusing when used with width/height as it conveys position than a dimension, maybe it should be renamed to LogicalUnit, PhysicalUnit and Unit or PixelUnit ?

Maybe `LogicalUnit`/`PhysicalUnit` is better.

2024-03-02 12:15 UTC, kchibisov approved these changes

2024-03-05 10:36 UTC, daxpedda approved these changes

2024-03-05 10:36 UTC, daxpedda commented on dpi/CHANGELOG.md
I guess we are fine with not also moving this changelog to docs.rs like in #3496?

2024-03-05 10:43 UTC, kchibisov commented on dpi/CHANGELOG.md
Yeah, it's not that important.

2024-03-08 15:49 UTC, notgull approved these changes

2024-03-08 17:15 UTC, merged