chore(changelog): use 'keep a changelog' format
rust-windowing/winit pull request #3590
Opened 2024-03-15 17:16 UTC by kchibisov

Links: https://keepachangelog.com/en/1.0.0/

--

I was thinking maybe we can try to _link_ the changed APIs, since it should be possible now?

I'm also not really liking the way the platform changes look. Maybe use a subsection for them? And for toplevel changes write with a `implemented on X, Y, and Z`?

2024-03-15 19:23 UTC, notgull approved these changes
Looks good to me!

2024-03-16 09:01 UTC, daxpedda requested changes
These have become pretty hard to read.

I do agree that now that we have headers for each change type, we shouldn't use the word "add" or "removed" in every entry, but it should still remain readable.

The main issue imo is starting sentences with "On Windows, ...", but then missing the verb, its really odd to read.

My suggestion would be to change the whole "On Windows, ..." to "**Windows: **".
Not a native speaker though, @notgull any thoughts?

2024-03-16 10:14 UTC, kchibisov commented
>My suggestion would be to change the whole "On Windows, ..." to "Windows: ".
Not a native speaker though, @notgull any thoughts?

Yeah, I don't like it as well as I said.

2024-03-16 23:07 UTC, notgull commented
I agree with adding the indicator before the actual addition.

2024-03-16 23:41 UTC, kchibisov commented
The alternative could be putting in the end of the sentence, which also makes it correct, or create sub sections, which is more clean.

2024-03-17 13:10 UTC, daxpedda commented
I'm in favor of sub sections.

2024-03-17 15:02 UTC, notgull commented
I'm fine with whichever option other maintainers prefer.

2024-03-21 17:54 UTC, madsmtm reviewed
From a user perspective, I think it's more interesting to see (in order, and roughly in the groups that I think are relevant):
- Large changes or reworks.
- Minor additions, changes, removals or deprecations.
- Changed platform-specific behaviour, with one section per platform.

Re grammar: For projects that use Keep A Changelog, I appreciate when they still add the header name (or something more descriptive) to each entry (e.g. `- Added services menu` over `- Services menu`). Changelogs are for humans, they don't have to be the absolute minimal they can be.

But don't have that strong of a preference here.

2024-03-26 09:34 UTC, daxpedda approved these changes
LGTM!

I agree with @madsmtm that this is for humans and therefor should be "human-friendly" and not minimal.
Lets wait for our meeting before merging.

2024-03-28 19:43 UTC, kchibisov commented
I've added a separate commit as alternative way to structure changelog.

2024-04-01 06:53 UTC, daxpedda requested changes
Now that we have sentences I think a dot at the end would be appropriate.

I missed the last meeting, did you decide to remove subsections or what happened here?

2024-04-01 14:12 UTC, kchibisov commented
@madsmtm suggested that we should write more correct sentences and subsections ones were harder to read, especially if you want to do inline migrations next to relevant change.

go ahead with fixing formatting as you like.

2024-04-12 11:51 UTC, madsmtm approved these changes
Fine with this now.

2024-04-12 17:38 UTC, merged