Silence clippy
rust-windowing/winit pull request #3604
Opened 2024-03-24 16:00 UTC by notgull

It appears that clippy's dead code detection has gotten better. This
commit fixes winit's code to match.

- [x] Tested on all platforms changed
- [x] Added an entry to the `changelog` module if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2024-03-24 16:05 UTC, kchibisov requested changes
I'd say that we shouldn't add that many `#[allow(dead_code)]` statements. Probably better to use other cfgs if we already adding one.

2024-03-24 16:07 UTC, notgull commented
@madsmtm The iOS failure in CI looks spurious to me, am I correct?

2024-03-24 16:09 UTC, notgull commented
> I'd say that we shouldn't add that many `#[allow(dead_code)]` statements. Probably better to use other cfgs if we already adding one.

In many cases we can't use `cfg(...)` guards to get around this issue, like for error types.

2024-03-24 19:02 UTC, madsmtm commented
> The iOS failure in CI looks spurious to me, am I correct?

I'd guess so

2024-03-26 09:49 UTC, daxpedda requested changes

2024-03-26 09:49 UTC, daxpedda commented on src/platform_impl/web/event_loop/state.rs
>          timeout: backend::Schedule,
```suggestion
        _timeout: backend::Schedule,
```
This is stored here for its drop behavior.

2024-03-26 09:49 UTC, daxpedda commented on src/platform_impl/web/event_loop/state.rs
>          request: backend::Schedule,
```suggestion
        _request: backend::Schedule,
```

2024-03-26 15:36 UTC, kchibisov approved these changes

2024-03-27 07:55 UTC, daxpedda approved these changes

2024-03-27 08:20 UTC, merged