bugfix(android): Allow `Volume*` keys to be passed to the user
rust-windowing/winit pull request #3636
Opened 2024-04-18 09:33 UTC by MarijnS95

It seems that discussions around #2748 (cc @Hoodad) being a poor workaround that should rather be implemented properly/differently drowned out the fact that the workaround was implemented incorrectly to begin with.  By having the `if` inside the match arm, rather than /on/ the match arm the `keycode =>` path is /never/ used for `Volume*` keys and this event is thus never passed on to the user, defeating the purpose of calling `handle_volume_keys()`.  Only the `Handled`/`Unhandled` state is affected by the `ignore_volume_keys` workaround, as set by `EventLoopBuilderExtAndroid::handle_volume_keys()`.

Fix this by moving the `if` workaround on the match arm, so that disabling it via `EventLoopBuilderExtAndroid::handle_volume_keys()` causes `Volume*` events to be delivered to user code once again.

- [x] Tested on all platforms changed
- [ ] Added an entry to the `changelog` module if knowledge of this change could be valuable to users
  - Where is that nowadays, if I want to backport this to `0.29.16`?
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

2024-04-18 10:22 UTC, madsmtm approved these changes

2024-04-18 16:58 UTC, kchibisov requested changes
Missing a changelog entry.

2024-04-18 17:15 UTC, Hoodad commented
Took me a while to see, but yes this should allow the users to react to input 👍 Thanks for the fix!

2024-04-22 13:00 UTC, kchibisov approved these changes

2024-04-23 17:51 UTC, merged