Reexport older versions of raw-window-handle
rust-windowing/winit pull request #3660
Opened 2024-04-27 18:10 UTC by linkmauve

When the user decides to use an older version of raw-window-handle, through the `rwh_04` or `rwh_05` features, it makes sense to reexport the crate so they don’t have to depend on it manually and can instead use `winit::raw_window_handle`.

- [x] Tested on all platforms changed
- [x] Added an entry to the `changelog` module if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior

2024-04-27 20:27 UTC, madsmtm approved these changes
Yeah, makes sense to me (not sure about the changelog categorization, is this a fix or an addition?)

2024-05-03 18:24 UTC, kchibisov requested changes

2024-05-03 18:24 UTC, kchibisov commented on src/changelog/unreleased.md
> +### Fixed
```suggestion
### Added
```

2024-05-06 15:19 UTC, kchibisov approved these changes
Renamed to avoid breaking change.

2024-05-06 15:50 UTC, merged