Implement ApplicationHandler for `&mut A`
rust-windowing/winit pull request #3709
Opened 2024-05-27 11:46 UTC by madsmtm

I'm not sure if there was a reason this implementation didn't exist before, but it's nice to have.

A future PR could change the signature of `run_app` from taking `&mut A` to just taking `A`.

- [x] Added an entry to the `changelog` module if knowledge of this change could be valuable to users

2024-05-27 17:58 UTC, notgull requested changes
I think we can also implement for `Box<A>`.

2024-05-27 17:58 UTC, notgull commented on src/application.rs
> +impl<A: ApplicationHandler<T>, T: 'static> ApplicationHandler<T> for &mut A {
Could we add a `?Sized` bound here to enable dynamic dispatch?

2024-05-28 18:19 UTC, madsmtm commented
> I think we can also implement for `Box<A>`.

You're right, have done so now.

2024-05-28 23:03 UTC, notgull approved these changes

2024-05-28 23:03 UTC, notgull commented on src/changelog/unreleased.md
> +- Implement `ApplicationHandler` for `&mut` references and boxes to something that implements `ApplicationHandler`.
Nit: boxes => heap allocations

2024-05-29 09:51 UTC, merged