iOS: Never queue application-level events
rust-windowing/winit pull request #3905
Opened 2024-09-10 09:52 UTC by madsmtm

Events like `resumed`, `new_events`, `about_to_wait`, and so on will never happen as a result of programmer action, so we'll never need to queue those. This allows us to remove the need for the old `Event` struct in the iOS backend.

Furthermore, we can now remove `InUserCallback`, since that state is already stored inside `EventHandler`.

I've tried to otherwise keep the semantics as close to the original by calling `handle_nonuser_events(mtm, [])`, which flushes pending events.

- [x] Tested on all platforms changed

2024-09-10 09:52 UTC, madsmtm commented
Incidentally, this fixes https://github.com/rust-windowing/winit/issues/3714, but makes https://github.com/rust-windowing/winit/issues/3816 much worse - not quite sure why yet?

2024-12-03 16:15 UTC, kchibisov requested changes
Commit should specify that it fixes specific issue you're talking about and you should have a changelog entry for it.

2024-12-03 17:26 UTC, madsmtm commented
I would treat the fact that it fixes https://github.com/rust-windowing/winit/issues/3714 as more of a curiosity, not a true fix, there's still a bunch of things I need to do to fully fix that issue. But I have added a changelog entry.

2024-12-03 17:30 UTC, kchibisov requested changes
>I would treat the fact that it fixes https://github.com/rust-windowing/winit/issues/3714 as more of a curiosity, not a true fix, there's still a bunch of things I need to do to fully fix that issue. But I have added a changelog entry.

In this case it shouldn't matter and it's better without it. And saying that it _fixes_ it should be removed, since it's not as you say.

2024-12-03 17:36 UTC, madsmtm commented
I've updated the comment

2024-12-03 17:50 UTC, madsmtm commented
That's why I didn't have a changelog entry in the first place ;)

But I think there is value in keeping the entry, while this is an implementation detail, it can be useful for users to know if something were to go wrong with it.

2024-12-03 17:55 UTC, kchibisov approved these changes
I just don't see how it's _actionable_ or solves issues, and I've asked for changelog only because you've said that it fixes some _old bug_. I'll leave it up to you though.

2024-12-03 18:04 UTC, madsmtm commented
Well, at the very least it should improve performance (once https://github.com/rust-windowing/winit/issues/3816 is also resolved), just because we do less. So just for that reason, the changelog entry is nice.

2024-12-03 18:53 UTC, merged