X11: Calculate ime cursor position correctly.
rust-windowing/winit pull request #3966
Opened 2024-10-23 21:37 UTC by xorgy

Fixes #3965

2024-10-23 21:49 UTC, kchibisov requested changes
This is generally not correct, though, since the intended way to do is to pass an area that shouldn't be obscured rather than offset. The concepts are different here, I'd say.

Probably something from `XNPreeditArea` is how it should work.

I generally won't block this patch, but it should be mentioned in the docs what it _does_ and probably we should suggest to pass just a _line_ generally for cursor to not hit bugs in various setups.

2024-10-24 15:52 UTC, xorgy commented
That's fair, I can add documentation changes to that effect, and a couple comments in the backend mentioning other possible ways to do preedit area reports (though I haven't found any IM servers implementing `PreeditArea` so far).

2024-10-25 18:19 UTC, xorgy commented
I've added more to the documentation about the behavior, and added comments for rationale.

2024-11-13 12:07 UTC, kchibisov approved these changes

2024-11-13 12:13 UTC, merged