Merge `KeyEventExtra` into `KeyEvent`
rust-windowing/winit pull request #4029
Opened 2024-12-03 10:35 UTC by madsmtm

To make the `text_with_all_modifiers` and `key_without_modifiers` fields easier to use, and to allow constructing `KeyEvent` in user test code. This also removes the need for `KeyEventExtModifierSupplement`.

Fixes https://github.com/rust-windowing/winit/issues/3606.

I went with adding the fields on all platforms, and just defining their behaviour as the same as `text`/`logical_key` on the unsupported platforms. This is similar to how we have all `WindowEvent`s available on all the platforms, but not all are emitted by all of them, so I felt this was a good trade-off.

- [ ] Tested on all platforms changed
- [x] Added an entry to the `changelog` module if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality

2024-12-03 10:37 UTC, madsmtm commented on src/event.rs
> +    pub key_without_modifiers: keyboard::Key,
Another option would be to make this an `Option<keyboard::Key>`, I'm not familiar enough with it to say what would be best.

2024-12-03 10:37 UTC, madsmtm commented on src/event.rs
> +    /// - **Web:** Unsupported, this field is always the same value as `text`.
Another option would be to always set `None` here on these platforms, but I felt this choice was more consistent with `key_without_modifiers` (unless we change that to be an `Option`).

2024-12-03 16:34 UTC, kchibisov requested changes
Could we have it the same way as before in a struct on a `KeyboardEvent` which you can not match, but can e.g. default init or set separately?

I don't really want to have an option to _match_ on those, since they are not cross platform. Other than that removing the extension is fine and it's not that big of a breaking change.

2024-12-03 16:45 UTC, madsmtm commented
> Could we have it the same way as before in a struct on a `KeyboardEvent` which you can not match, but can e.g. default init or set separately?

Hmm, I can, but I kinda feel like that'd just be unnecessary indirection? And I guess it we really want users to be able to test their crates, they'll need the ability to set the fields in this extra struct anyhow?

> I don't really want to have an option to _match_ on those, since they are not cross platform. Other than that removing the extension is fine and it's not that big of a breaking change.

Am I understanding correctly that your worry is that users may be more aware of a method not being cross-platform, as opposed to a field being so?

2024-12-03 16:56 UTC, kchibisov commented
Yes, so it's an `Option` and you should account for it explicitly. If it's not an option you will kind of assume that it works, where on e.g. some it'll always fail. You can just default initialize it, I don't see an issue with it. Yes you won't be able to test the values you have in `text_with_all_modifiers`, but you write the keys yourself, so can write whatever in regular fields, so it doesn't really matter.

2025-02-24 02:41 UTC, madsmtm commented
I've been thinking about this again, and I don't think there's a good reason why these are treated differently from the other `KeyEvent` fields.

Remember that the fact that `text_with_all_modifiers` and `key_without_modifiers` doesn't work on Android/iOS is merely an artifact of the current implementation, they very much _could_ work there. The only platform where the situation may be a bit different is Web, but even there, we could probably implement it? At least `text_with_all_modifiers` is "just" a matter of mapping [`key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) + check [`ctrlKey`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/ctrlKey) according to [a basic ASCII table](https://ss64.com/ascii.html), no?

Basically, I'm arguing that these APIs are _supportable_ on all platforms, and hence should be available everywhere too; just like `WindowEvent::Moved` is available everywhere, even though it's not yet implemented on many platforms.

2025-02-26 08:22 UTC, kchibisov approved these changes
I think it's fine, I don't like this API at all, and would just deprecate it incrementally in the future by having `KeyboardHanlingV1` and `V2` where `V1` is implemented via `V2` and apps supporting `V2` will get something more reliable.

2025-02-26 16:51 UTC, merged