Window attribute
rust-windowing/winit pull request #4039
Opened 2024-12-13 16:39 UTC by Mehrbod2002

-  Add window attribute to retrieve because of custom handlers in our system and frameworks .

2024-12-13 16:46 UTC, madsmtm requested changes
First off, you seem to have based this on the `v0.30.x` branch, please rebase on top of `master`.

Apart from that, I'm not sure I want to accept this, at least not without a clearer use-case description? The attributes are not being kept up to date with the state in the Window, so it seems mostly useless?

2024-12-13 18:45 UTC, Mehrbod2002 commented
@madsmtm 

As an example I am going to use it in dixous in customized way to use winit instead gtk .

So to use in custom event handler and when user want to use method like with_window and transfer to between platforms .

I got response from this merge and satisfied and do it in this version because of rwh_06 which is needed too .

2024-12-13 23:20 UTC, madsmtm commented
Could you show a piece of example code for how you'd use it?

> do it in this version because of rwh_06 which is needed too .

`raw-window-handle v0.6` is used on the `master` branch too. Besides, this is a feature (not a bug fix), so we're unlikely to release it as part of the `v0.30.x` series.

2024-12-14 06:30 UTC, Mehrbod2002 commented
@madsmtm 
review this issue and its source as an example :
https://github.com/DioxusLabs/dioxus/issues/2706

2024-12-14 06:51 UTC, madsmtm commented
I'm sorry, that issue doesn't really explain anything to me? How is it linked with the feature your implementing here?

And why does Dioxus need the `WindowAttributes` to be available on Winit's `Window`, why can it not store the attributes itself externally? E.g. why is the following not adequate?
```rust
pub struct DioxusWindow {
    pub window: winit::window::Window,
    pub attributes: winit::window::WindowAttributes,
}
```

2024-12-14 06:58 UTC, Mehrbod2002 commented
It's so clear . we need window attributes for creating window and need to be use raw window and display in platforms .

don't store in struct in dioxus because some method not defined to retrieve . for example how to retrieve blur or transparent ?.

If not reasonable please close this PR .

2024-12-14 18:31 UTC, madsmtm commented
> It's so clear . we need window attributes for creating window and need to be use raw window and display in platforms .

But why do you need the same attributes as what you created the first window with? Can you not use `Window::default_attributes()`, and modify it to match your needs?

> for example how to retrieve blur or transparent ?.

That's true, we don't have a way to retrieve those - but that isn't solved by this PR either?

I'd be happy accepting a PR that added getters `Window::is_blur(&self) -> bool` or `Window::is_transparent(&self) -> bool`.

> If not reasonable please close this PR .

I'm inclined to, but honestly mostly because I have a hard time understanding you (apologies!). I'm not sure what to do about that, maybe try to put your thoughts into more words?

2025-01-08 17:19 UTC, closed without merging